config/routes.rb
TicTacToeRails4::Application.routes.draw do

  root 'home#index'
  resource :home, :only => [], :controller => :home do
    member do
      get :current_game
      get :reset
      post :step
      get :recent_games
    end
  end

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  scope :recent, ->(num) do
    order(:created_at => :desc).limit(num)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'tic_tac_toe'

class HomeController < ApplicationController
  respond_to :html, :json

  TOP_GAMES_COUNT = 10

  def index
  end

  def current_game
    render :json => game.to_json
  end

  def step
    game.turn(point, current_player)

    finished, winner = game.finished?, game.winner

    if finished
      winner_sign = winner ? winner.sign : 'draw'
      Game.create!(:winner => winner_sign)
    end

    render :json => {
      :finished => finished,
      :winner => winner
    }.to_json
  end

  def reset
    session.delete(:game)
    @_game = nil
    redirect_to root_path
  end

  def recent_games
    @games = Game.recent(TOP_GAMES_COUNT)
  end

private

  def point
    TicTacToe::Point.new(params[:x].to_i, params[:y].to_i)
  end

  def game
    @_game ||= begin
      session[:game] ||= TicTacToe::Game.new
    end
  end

  def current_player
    game.players[params[:current_player].intern]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%br.clear

%table.table.table-bordered#board
  %tr
    %td{:"data-pos-x" => "0", :"data-pos-y" => "0"}
    %td{:"data-pos-x" => "0", :"data-pos-y" => "1"}
    %td{:"data-pos-x" => "0", :"data-pos-y" => "2"}
  %tr
    %td{:"data-pos-x" => "1", :"data-pos-y" => "0"}
    %td{:"data-pos-x" => "1", :"data-pos-y" => "1"}
    %td{:"data-pos-x" => "1", :"data-pos-y" => "2"}
  %tr
    %td{:"data-pos-x" => "2", :"data-pos-y" => "0"}
    %td{:"data-pos-x" => "2", :"data-pos-y" => "1"}
    %td{:"data-pos-x" => "2", :"data-pos-y" => "2"}

app/views/home/recent_games.html.haml
%ul.recent_games
  - @games.each do |game|
    %li
      %span.red
        =game.winner
      (#{game.created_at})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TicTacToeRails4" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Tic-Tac-Toe Game</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Reset", reset_home_path  %></li>
              <li><%= link_to "History", recent_games_home_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Reset", reset_home_path %></li>
                <li><%= link_to "History", recent_games_home_path  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; SlotPartners 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>